version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: musicstore_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: cmd/user-service/Dockerfile
    container_name: user_service
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${PORT}:${PORT}"

volumes:
  postgres_data:
